server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address:true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: microservice-employee
          uri: lb://microservice-user  # Nombre del microservicio donde está el controlador
          predicates:
            - Path=/employee/**
        - id: microservice-costumer
          uri: lb://microservice-user  # Mismo microservicio, pero diferente ruta
          predicates:
            - Path=/costumer/**
        - id: microservice-creditRequest
          uri: lb://microservice-creditRequest
          predicates:
            - Path=/creditRequest/**
        - id: microservice-document
          uri: lb://microservice-creditRequest
          predicates:
            - Path=/document/**
        - id: microservice-creditEvaluation
          uri: lb://microservice-creditEvaluation
          predicates:
            - Path=/creditEvaluation/**
        - id: microservice-calculations
          uri: lb://microservice-calculations
          predicates:
            - Path=/calculations/**
        - id: microservice-tracking
          uri: lb://microservice-tracking
          predicates:
            - Path=/tracking/**