apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-gateway-deployment
  labels:
    app: microservice-gateway-deployment
spec:
  selector:
    matchLabels:
      app: microservice-gateway-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-gateway-deployment
    spec:
      containers:
        - name: microservice-gateway
          image: cvstleee/microservice-gateway:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://microservice-config:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://microservice-eureka:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-gateway
  labels:
    app: microservice-gateway
spec:
  selector:
    app: microservice-gateway-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer