apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-calculations-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-calculations-deployment
  template:
    metadata:
      labels:
        app: microservice-calculations-deployment
    spec:
      containers:
        - name: microservice-calculations-container
          image: cvstleee/microservice-calculations:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://microservice-config:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://microservice-eureka:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_CALCULATIONS
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_CALCULATIONS
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD