apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-config-deployment
  labels:
    app: microservice-config-deployment
spec:
  selector:
    matchLabels:
      app: microservice-config-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-config-deployment
    spec:
      containers:
        - name: microservice-config
          image: cvstleee/microservice-config:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-config
  labels:
    app: microservice-config
spec:
  selector:
    app: microservice-config-deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer