apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  POSTGRES_DB_HOST: postgres
  POSTGRES_DB_USER: userprestabancodb
  POSTGRES_DB_CREDITREQUEST: creditrequestprestabancodb
  POSTGRES_DB_CREDITEVALUATION: creditevaluationprestabancodb
  POSTGRES_DB_CALCULATIONS: calculationsprestabancodb
  POSTGRES_DB_TRACKING: trackingprestabancodb
